#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-protobuf-java
Version  : 2.4.1
Release  : 1
URL      : https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar
Source0  : https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar
Source1  : https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-protobuf-java-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-protobuf-java package.
Group: Data

%description data
data components for the mvn-protobuf-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/protobuf/protobuf-java/2.4.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/google/protobuf/protobuf-java/2.4.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/protobuf/protobuf-java/2.4.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/protobuf/protobuf-java/2.4.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar
/usr/share/java/.m2/repository/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.pom
